apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patient-api-nginx
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=mofwili/easy-nginx
    #argocd-image-updater.argoproj.io/nginx.update-strategy: newest-build
    argocd-image-updater.argoproj.io/nginx.update-strategy: semver
    argocd-image-updater.argoproj.io/nginx.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/nginx.ignore-tags: "*"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    # âœ… CHANGE: Use "values" for Helm, not "kustomization"
    argocd-image-updater.argoproj.io/nginx.write-back-target: values
spec:
  project: default
  source:
    repoURL: https://github.com/vasplustechnologies/easy-nginx-demosite-k8s-manifests.git
    targetRevision: main
    path: apps/nginx-app/canary
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: easy-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true